### ISSUE TITLE
Math domain error during process_tongs()

### ISSUE THREAD

**Issue by hello-binit** [hello-robot/stretch_dex_teleop#2]
Hello, using dex teleop with the default arguments, I've encountered this error during normal teleop usage which leads to the process exiting:

```
Traceback (most recent call last):
  File "/home/hello-robot/repos/stretch_dex_teleop/dex_teleop.py", line 63, in <module>
    markers = webcam_aruco_detector.process_next_frame()
  File "/home/hello-robot/repos/stretch_dex_teleop/webcam_teleop_interface.py", line 443, in process_next_frame
    virtual_tongs_marker = self.process_tongs(markers)
  File "/home/hello-robot/repos/stretch_dex_teleop/webcam_teleop_interface.py", line 407, in process_tongs
    adjacent_side = math.sqrt((hypotenuse * hypotenuse) - (opposite_side * opposite_side))
ValueError: math domain error
Webcam.__del__: releasing the OpenCV camera.
GripperToGoal.__del__: stopping the robot
Exception ignored in: <function GripperToGoal.__del__ at 0x744f54805fc0>
Traceback (most recent call last):
  File "/home/hello-robot/repos/stretch_dex_teleop/gripper_to_goal.py", line 129, in __del__
  File "/home/hello-robot/repos/stretch_body/body/stretch_body/robot.py", line 358, in stop
  File "/home/hello-robot/repos/stretch_body/body/stretch_body/dynamixel_X_chain.py", line 111, in stop
  File "/home/hello-robot/repos/stretch_body/body/stretch_body/dynamixel_hello_XL430.py", line 254, in stop
  File "/home/hello-robot/repos/stretch_body/body/stretch_body/dynamixel_hello_XL430.py", line 552, in disable_torque
  File "/home/hello-robot/repos/stretch_body/body/stretch_body/dynamixel_XL430.py", line 455, in disable_torque
  File "/home/hello-robot/repos/stretch_body/body/stretch_body/dynamixel_XL430.py", line 127, in __exit__
  File "/usr/lib/python3.10/signal.py", line 56, in signal
TypeError: signal handler must be signal.SIG_IGN, signal.SIG_DFL, or a callable object
$
```

**Comment by mlamsey** [comment]
```
adjacent_side = math.sqrt((hypotenuse * hypotenuse) - (opposite_side * opposite_side))
```

**Comment by hilookas** [comment]
This is caused by wrong unit convertion of aruco tag. The tag position in the space is incorrect (with wrong scale). Try to open the ring light and calibrate the camera again.
